[project]
name = "repl-nix-tokensizer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ebooklib>=0.18",
    "html2text>=2024.2.26",
    "openpyxl>=3.1.5",
    "pypdf2>=3.0.1",
    "python-docx>=1.1.2",
    "pyyaml>=6.0.2",
    "streamlit>=1.39.0",
    "striprtf>=0.0.26",
    "tiktoken>=0.8.0",
]
